# This file was automatically generated by SWIG (http://www.swig.org).
# Version 4.0.2
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info < (2, 7, 0):
    raise RuntimeError("Python 2.7 or later required")

# Import the low-level C/C++ module
if __package__ or "." in __name__:
    from . import _unit
else:
    import _unit

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)


def _swig_setattr_nondynamic_instance_variable(set):
    def set_instance_attr(self, name, value):
        if name == "thisown":
            self.this.own(value)
        elif name == "this":
            set(self, name, value)
        elif hasattr(self, name) and isinstance(getattr(type(self), name), property):
            set(self, name, value)
        else:
            raise AttributeError("You cannot add instance attributes to %s" % self)
    return set_instance_attr


def _swig_setattr_nondynamic_class_variable(set):
    def set_class_attr(cls, name, value):
        if hasattr(cls, name) and not isinstance(getattr(cls, name), property):
            set(cls, name, value)
        else:
            raise AttributeError("You cannot add class attributes to %s" % cls)
    return set_class_attr


def _swig_add_metaclass(metaclass):
    """Class decorator for adding a metaclass to a SWIG wrapped class - a slimmed down version of six.add_metaclass"""
    def wrapper(cls):
        return metaclass(cls.__name__, cls.__bases__, cls.__dict__.copy())
    return wrapper


class _SwigNonDynamicMeta(type):
    """Meta class to enforce nondynamic attributes (no new attributes) for a class"""
    __setattr__ = _swig_setattr_nondynamic_class_variable(type.__setattr__)


class SwigPyIterator(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _unit.delete_SwigPyIterator

    def value(self):
        return _unit.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _unit.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _unit.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _unit.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _unit.SwigPyIterator_equal(self, x)

    def copy(self):
        return _unit.SwigPyIterator_copy(self)

    def next(self):
        return _unit.SwigPyIterator_next(self)

    def __next__(self):
        return _unit.SwigPyIterator___next__(self)

    def previous(self):
        return _unit.SwigPyIterator_previous(self)

    def advance(self, n):
        return _unit.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _unit.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _unit.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _unit.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _unit.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _unit.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _unit.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self

# Register SwigPyIterator in _unit:
_unit.SwigPyIterator_swigregister(SwigPyIterator)

class IntVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _unit.IntVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _unit.IntVector___nonzero__(self)

    def __bool__(self):
        return _unit.IntVector___bool__(self)

    def __len__(self):
        return _unit.IntVector___len__(self)

    def __getslice__(self, i, j):
        return _unit.IntVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _unit.IntVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _unit.IntVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _unit.IntVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _unit.IntVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _unit.IntVector___setitem__(self, *args)

    def pop(self):
        return _unit.IntVector_pop(self)

    def append(self, x):
        return _unit.IntVector_append(self, x)

    def empty(self):
        return _unit.IntVector_empty(self)

    def size(self):
        return _unit.IntVector_size(self)

    def swap(self, v):
        return _unit.IntVector_swap(self, v)

    def begin(self):
        return _unit.IntVector_begin(self)

    def end(self):
        return _unit.IntVector_end(self)

    def rbegin(self):
        return _unit.IntVector_rbegin(self)

    def rend(self):
        return _unit.IntVector_rend(self)

    def clear(self):
        return _unit.IntVector_clear(self)

    def get_allocator(self):
        return _unit.IntVector_get_allocator(self)

    def pop_back(self):
        return _unit.IntVector_pop_back(self)

    def erase(self, *args):
        return _unit.IntVector_erase(self, *args)

    def __init__(self, *args):
        _unit.IntVector_swiginit(self, _unit.new_IntVector(*args))

    def push_back(self, x):
        return _unit.IntVector_push_back(self, x)

    def front(self):
        return _unit.IntVector_front(self)

    def back(self):
        return _unit.IntVector_back(self)

    def assign(self, n, x):
        return _unit.IntVector_assign(self, n, x)

    def resize(self, *args):
        return _unit.IntVector_resize(self, *args)

    def insert(self, *args):
        return _unit.IntVector_insert(self, *args)

    def reserve(self, n):
        return _unit.IntVector_reserve(self, n)

    def capacity(self):
        return _unit.IntVector_capacity(self)
    __swig_destroy__ = _unit.delete_IntVector

# Register IntVector in _unit:
_unit.IntVector_swigregister(IntVector)

class DoubleVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _unit.DoubleVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _unit.DoubleVector___nonzero__(self)

    def __bool__(self):
        return _unit.DoubleVector___bool__(self)

    def __len__(self):
        return _unit.DoubleVector___len__(self)

    def __getslice__(self, i, j):
        return _unit.DoubleVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _unit.DoubleVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _unit.DoubleVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _unit.DoubleVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _unit.DoubleVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _unit.DoubleVector___setitem__(self, *args)

    def pop(self):
        return _unit.DoubleVector_pop(self)

    def append(self, x):
        return _unit.DoubleVector_append(self, x)

    def empty(self):
        return _unit.DoubleVector_empty(self)

    def size(self):
        return _unit.DoubleVector_size(self)

    def swap(self, v):
        return _unit.DoubleVector_swap(self, v)

    def begin(self):
        return _unit.DoubleVector_begin(self)

    def end(self):
        return _unit.DoubleVector_end(self)

    def rbegin(self):
        return _unit.DoubleVector_rbegin(self)

    def rend(self):
        return _unit.DoubleVector_rend(self)

    def clear(self):
        return _unit.DoubleVector_clear(self)

    def get_allocator(self):
        return _unit.DoubleVector_get_allocator(self)

    def pop_back(self):
        return _unit.DoubleVector_pop_back(self)

    def erase(self, *args):
        return _unit.DoubleVector_erase(self, *args)

    def __init__(self, *args):
        _unit.DoubleVector_swiginit(self, _unit.new_DoubleVector(*args))

    def push_back(self, x):
        return _unit.DoubleVector_push_back(self, x)

    def front(self):
        return _unit.DoubleVector_front(self)

    def back(self):
        return _unit.DoubleVector_back(self)

    def assign(self, n, x):
        return _unit.DoubleVector_assign(self, n, x)

    def resize(self, *args):
        return _unit.DoubleVector_resize(self, *args)

    def insert(self, *args):
        return _unit.DoubleVector_insert(self, *args)

    def reserve(self, n):
        return _unit.DoubleVector_reserve(self, n)

    def capacity(self):
        return _unit.DoubleVector_capacity(self)
    __swig_destroy__ = _unit.delete_DoubleVector

# Register DoubleVector in _unit:
_unit.DoubleVector_swigregister(DoubleVector)

class PrimeUnitVector(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr

    def iterator(self):
        return _unit.PrimeUnitVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _unit.PrimeUnitVector___nonzero__(self)

    def __bool__(self):
        return _unit.PrimeUnitVector___bool__(self)

    def __len__(self):
        return _unit.PrimeUnitVector___len__(self)

    def __getslice__(self, i, j):
        return _unit.PrimeUnitVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _unit.PrimeUnitVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _unit.PrimeUnitVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _unit.PrimeUnitVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _unit.PrimeUnitVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _unit.PrimeUnitVector___setitem__(self, *args)

    def pop(self):
        return _unit.PrimeUnitVector_pop(self)

    def append(self, x):
        return _unit.PrimeUnitVector_append(self, x)

    def empty(self):
        return _unit.PrimeUnitVector_empty(self)

    def size(self):
        return _unit.PrimeUnitVector_size(self)

    def swap(self, v):
        return _unit.PrimeUnitVector_swap(self, v)

    def begin(self):
        return _unit.PrimeUnitVector_begin(self)

    def end(self):
        return _unit.PrimeUnitVector_end(self)

    def rbegin(self):
        return _unit.PrimeUnitVector_rbegin(self)

    def rend(self):
        return _unit.PrimeUnitVector_rend(self)

    def clear(self):
        return _unit.PrimeUnitVector_clear(self)

    def get_allocator(self):
        return _unit.PrimeUnitVector_get_allocator(self)

    def pop_back(self):
        return _unit.PrimeUnitVector_pop_back(self)

    def erase(self, *args):
        return _unit.PrimeUnitVector_erase(self, *args)

    def __init__(self, *args):
        _unit.PrimeUnitVector_swiginit(self, _unit.new_PrimeUnitVector(*args))

    def push_back(self, x):
        return _unit.PrimeUnitVector_push_back(self, x)

    def front(self):
        return _unit.PrimeUnitVector_front(self)

    def back(self):
        return _unit.PrimeUnitVector_back(self)

    def assign(self, n, x):
        return _unit.PrimeUnitVector_assign(self, n, x)

    def resize(self, *args):
        return _unit.PrimeUnitVector_resize(self, *args)

    def insert(self, *args):
        return _unit.PrimeUnitVector_insert(self, *args)

    def reserve(self, n):
        return _unit.PrimeUnitVector_reserve(self, n)

    def capacity(self):
        return _unit.PrimeUnitVector_capacity(self)
    __swig_destroy__ = _unit.delete_PrimeUnitVector

# Register PrimeUnitVector in _unit:
_unit.PrimeUnitVector_swigregister(PrimeUnitVector)

class PrimeUnit(object):
    thisown = property(lambda x: x.this.own(), lambda x, v: x.this.own(v), doc="The membership flag")
    __repr__ = _swig_repr
    x = property(_unit.PrimeUnit_x_get, _unit.PrimeUnit_x_set)
    y = property(_unit.PrimeUnit_y_get, _unit.PrimeUnit_y_set)

    def __init__(self, *args):
        _unit.PrimeUnit_swiginit(self, _unit.new_PrimeUnit(*args))

    def check_requests(self, units, kinds_of_bases):
        return _unit.PrimeUnit_check_requests(self, units, kinds_of_bases)

    def listen(self, units, unit, base_kind):
        return _unit.PrimeUnit_listen(self, units, unit, base_kind)
    __swig_destroy__ = _unit.delete_PrimeUnit

# Register PrimeUnit in _unit:
_unit.PrimeUnit_swigregister(PrimeUnit)



